# Generated by Django 5.1.5 on 2025-04-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrbanFit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('shoes', 'Shoes'), ('accessories', 'Accessories')], max_length=11)),
                ('image', models.ImageField(upload_to='products/')),
                ('color', models.CharField(max_length=200)),
            ],
        ),
    ]
